In [2]:
# Importing required Libraries

import pandas as pd
from tabulate import tabulate
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [3]:
# Loading the dummy dataset

data = pd.read_csv(r"movie.csv")

In [4]:
data

# 1 representa Male
# 0 represents Female

    age  gender      genre
0    20       1     Action
1    23       1     Action
2    25       1     Action
3    26       1   Thriller
4    29       1   Thriller
5    30       1   Thriller
6    31       1      Drama
7    33       1      Drama
8    37       1      Drama
9    20       0  Animation
10   21       0  Animation
11   25       0  Animation
12   26       0   Romantic
13   27       0   Romantic
14   30       0   Romantic
15   31       0    Musical
16   34       0    Musical
17   35       0    Musical

In [5]:
# Processing data for out requirement

X = data.drop(columns=['genre'])
Y = data['genre']

In [29]:
total = 0
n=10
for i in range (0,n):
    XTrain, XTest, YTrain, YTest =train_test_split(X,Y,test_size=0.2)
    model = DecisionTreeClassifier()
    model.fit(XTrain,YTrain)
    prediction = model.predict(XTest)
    score = accuracy_score(YTest, prediction)
    print("Acuracy of our prediction : ", score)
    total += score

avg = total/n
print("\n\nAverage accuracy of our prediction :", avg)

Acuracy of our prediction :  1.0
Acuracy of our prediction :  1.0
Acuracy of our prediction :  1.0
Acuracy of our prediction :  1.0
Acuracy of our prediction :  1.0
Acuracy of our prediction :  1.0
Acuracy of our prediction :  1.0
Acuracy of our prediction :  0.75
Acuracy of our prediction :  1.0
Acuracy of our prediction :  0.25


Average accuracy of our prediction : 0.9